// UI Elements
const els = {
  hpBar: document.getElementById('hp-bar'),
  scene: document.getElementById('scene'),
  interactiveLayer: document.getElementById('interactive-layer'),
  dialogueBox: document.getElementById('dialogue-box'),
  dialogueText: document.getElementById('dialogue-text'),
  dialogueBtn: document.getElementById('dialogue-close'),
  deathScreen: document.getElementById('death-screen'),
  deathReason: document.getElementById('death-reason'),
  restartBtn: document.getElementById('restart-btn'),
  winScreen: document.getElementById('win-screen'),
  logList: document.getElementById('log-list'),
  inventorySlots: document.querySelectorAll('.slot'),
  hintBtn: document.getElementById('hint-btn'),
  actionLogToggle: document.getElementById('toggle-action-log'),
  actionLogContainer: document.getElementById('action-log-container'),
  actionLogList: document.getElementById('action-log-list'),
  actionLogContent: document.getElementById('action-log-content'),
  pillUiContainer: document.getElementById('pill-ui-container'),
  pillOptions: document.getElementById('pill-options'),
  faucetUiContainer: document.getElementById('faucet-ui-container'),
  waterGaugeFill: document.getElementById('water-gauge-fill'),
  waterVolText: document.getElementById('water-volume-text'),
  waterTempText: document.getElementById('water-temp-text'),
  kitchenUiContainer: document.getElementById('kitchen-ui-container'),
  ingredientOptions: document.getElementById('ingredient-options'),
  stoveUiContainer: document.getElementById('stove-ui-container'),
  stoveInputDisplay: document.getElementById('stove-input-display'),
  diningUiContainer: document.getElementById('dining-ui-container'),
  drinkOptions: document.getElementById('drink-options'),
  flashlightMask: document.getElementById('flashlight-mask'),
  flashlightUiContainer: document.getElementById('flashlight-ui-container'),
  flashlightToggleBtn: document.getElementById('flashlight-toggle-btn'),
  flashlightChargeBtn: document.getElementById('flashlight-charge-btn'),
  batteryText: document.getElementById('battery-text')
};
